### ISSUE TITLE
在GLUE数据集上测试，程序报错

### ISSUE THREAD

**Issue by hongliang-wei** [fundamentalvision/Uni-Perceiver#11]
CoLA:
<details><summary>GLUE_CoLA.yaml</summary>
<p>

```yaml
   _BASE_: "base.yaml"

    SHARED_TARGETS:
      - 
        NAME: 'CoLA'
        SHARED_TARGETS_CFG:
          FILE_PATH: '/mnt/14T-disk/code/Uni-Perceiver5/datasets/GLUE_classnames/CoLA_class_name_CLIP_with_endoftext.pkl'
          DISTRIBUTED: False
    TASKS:
      -
        NAME: CoLA
        DATASETS:
          TRAIN: 'GLUEDataset'
          TEST: 'GLUEDataset'
          #VAL: 'GLUEDataset'
          TASK_TYPE: 'text_classification'
          DATASET_NAME: 'CoLA'
          TARGET_SET: ['CoLA']
        DATALOADER:
          TRAIN_BATCH_SIZE: 16
          TEST_BATCH_SIZE: 64
          NUM_WORKERS: 4
          ANNO_FOLDER:  '/mnt/14T-disk/code/Uni-Perceiver5/datasets/bert_pretrain_data/glue_data/'
    
    
        MODEL:
          MAX_SEQ_LEN: 256
          TEMP_NAME: logit_scale_text_mlm
        LOSSES:
          NAMES: ['LabelSmoothingCrossEntropy', 'Accuracy']
          LABELSMOOTHING: 0.1
          # LOSS_WEIGHT: 1
          REDUCTION: 'mean'
          LOSS_FP32: False
        INFERENCE:
          NAME: 'GLUEEvaler'
          VOCAB: 'CLIP'
          GENERATION_MODE: False
    
    
      
    
    ENGINE:
      NAME: 'UnifiedTrainer'
    
    DATALOADER:
      USE_WEIGHTED_SAMPLER: True
      UNIFIED_DATASET: True 
      NUM_WORKERS: 16
    
    ######################################### MODEL #########################################
    MODEL:
      MODEL_EMA: False
      MODEL_EMA_DECAY: 0.9999
      
    ####################################### Optimizer #######################################
    SOLVER:
      NAME: 'Adam'
      # EPOCH: 1
      MAX_ITER: 5600
      CHECKPOINT_PERIOD: 1000000
      EVAL_PERIOD: 200
      CHECKPOINT_MAX_SAVE: 1
      BASE_LR: 0.00001
      BIAS_LR_FACTOR: 1.0
      WEIGHT_DECAY: 0.1
      WEIGHT_DECAY_NORM: 0.0
      WEIGHT_DECAY_BIAS: 0.0
      MOMENTUM: 0.9
      DAMPENING: 0.0
      NESTEROV: 0.0
      BETAS: [0.9, 0.98]
      EPS: 1e-8
      GRAD_CLIP: 0.5
      GRAD_CLIP_TYPE: 'norm'
      ACCUM_ITER: 0
      AMP_FP16: True
      APEX_FP16: False # dangerous
      WRITE_PERIOD: 20
      
    ####################################### lr scheduler ####################################### 
    LR_SCHEDULER:
      NAME: 'WarmupCosine'
      WARMUP: 400
      MIN_LR: 0.00000001
    
    
    
    find_unused_parameters: true

```

</p>
</details>

<details><summary>error</summary>
<p>

```
   Traceback (most recent call last):
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 171, in <module>
    Traceback (most recent call last):
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 171, in <module>
        main(args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 113, in main
        trainer = build_engine(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/build.py", line 10, in build_engine
        engine = ENGINE_REGISTRY.get(cfg.ENGINE.NAME)(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_trainer.py", line 117, in __init__
        main(args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 113, in main
        self.test_data_loader = build_test_loader(cfg, self.task_cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/utils/engine_util.py", line 74, in build_test_loader
        trainer = build_engine(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/build.py", line 10, in build_engine
            loaders[name] = build_standard_valtest_loader(new_cfg, task_cfg, stage='test', multi_gpu_eval=multi_gpu)engine = ENGINE_REGISTRY.get(cfg.ENGINE.NAME)(cfg)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 327, in build_standard_valtest_loader
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_trainer.py", line 117, in __init__
        self.test_data_loader = build_test_loader(cfg, self.task_cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/utils/engine_util.py", line 74, in build_test_loader
        dataset = build_dataset_mapper(cfg, name=dataset_name, stage=stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 41, in build_dataset_mapper
        loaders[name] = build_standard_valtest_loader(new_cfg, task_cfg, stage='test', multi_gpu_eval=multi_gpu)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 327, in build_standard_valtest_loader
        dataset_mapper = DATASETS_REGISTRY.get(name)(cfg, stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/config/config.py", line 211, in wrapped
        dataset = build_dataset_mapper(cfg, name=dataset_name, stage=stage)    
    init_func(self, **explicit_args)  File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 41, in build_dataset_mapper
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 59, in __init__
        dataset_mapper = DATASETS_REGISTRY.get(name)(cfg, stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/config/config.py", line 211, in wrapped
        self.load_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 159, in load_data
            datalist = self.load_raw_data(cfg)init_func(self, **explicit_args)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 225, in load_raw_data
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 59, in __init__
        self.load_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 159, in load_data
        label = float(sensinfo[self.label_column - 1])
    ValueError: could not convert string to float: 'Bill whistled past the house.'
        datalist = self.load_raw_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 225, in load_raw_data
        label = float(sensinfo[self.label_column - 1])
    ValueError: could not convert string to float: 'Bill whistled past the house.'
```

</p>
</details>
#######################################################
<details><summary>GLUE_MNLI.yaml</summary>
<p>

```yaml
  _BASE_: "base.yaml"
  
  SHARED_TARGETS:
    - 
      NAME: 'MNLI'
      SHARED_TARGETS_CFG:
        FILE_PATH: '/mnt/14T-disk/code/Uni-Perceiver5/datasets/GLUE_classnames/MNLI_class_name_CLIP_with_endoftext.pkl'
        DISTRIBUTED: False
  
  TASKS:
    -
      NAME: MNLI
      DATASETS:
        TRAIN: 'GLUEDataset'
        TEST: 'GLUEDataset'
        #VAL: 'GLUEDataset'
        TASK_TYPE: 'text_classification'
        DATASET_NAME: 'MNLI_Match'
        TARGET_SET: ['MNLI']
      DATALOADER:
        TRAIN_BATCH_SIZE: 32
        TEST_BATCH_SIZE: 32
        NUM_WORKERS: 4
        ANNO_FOLDER:  '/mnt/14T-disk/code/Uni-Perceiver5/datasets/bert_pretrain_data/glue_data/'
  
      MODEL:
        MAX_SEQ_LEN: 256
        TEMP_NAME: logit_scale_text_mlm
      LOSSES:
        NAMES: ['LabelSmoothingCrossEntropy', 'Accuracy']
        LABELSMOOTHING: 0.1
        # LOSS_WEIGHT: 1
        REDUCTION: 'mean'
        LOSS_FP32: False
      INFERENCE:
        NAME: 'GLUEEvaler'
        VOCAB: 'CLIP'
        GENERATION_MODE: False
  
  
    
  
  ENGINE:
    NAME: 'UnifiedTrainer'
  
  DATALOADER:
    USE_WEIGHTED_SAMPLER: True
    UNIFIED_DATASET: True 
    NUM_WORKERS: 16
  
  ######################################### MODEL #########################################
  MODEL:
    MODEL_EMA: False
    MODEL_EMA_DECAY: 0.9999
  
  
  ####################################### Optimizer #######################################
  SOLVER:
    NAME: 'Adam'
    MAX_ITER: 125000
    CHECKPOINT_PERIOD: 125000
    EVAL_PERIOD: 5000
    CHECKPOINT_MAX_SAVE: 1
    BASE_LR: 0.00001
    BIAS_LR_FACTOR: 1.0
    WEIGHT_DECAY: 0.1
    WEIGHT_DECAY_NORM: 0.0
    WEIGHT_DECAY_BIAS: 0.0
    MOMENTUM: 0.9
    DAMPENING: 0.0
    NESTEROV: 0.0
    BETAS: [0.9, 0.98]
    EPS: 1e-8
    GRAD_CLIP: 0.5
    GRAD_CLIP_TYPE: 'norm'
    ACCUM_ITER: 0
    AMP_FP16: True
    APEX_FP16: False # dangerous
    WRITE_PERIOD: 20
    
  ####################################### lr scheduler ####################################### 
  LR_SCHEDULER:
    NAME: 'WarmupCosine'
    WARMUP: 7500
    MIN_LR: 0.00000001
  
  
  
  find_unused_parameters: true
```

</p>
</details>

<details><summary>error</summary>
<p>

```
    Traceback (most recent call last):
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 171, in <module>
        main(args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 113, in main
        trainer = build_engine(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/build.py", line 10, in build_engine
        engine = ENGINE_REGISTRY.get(cfg.ENGINE.NAME)(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_trainer.py", line 117, in __init__
        self.test_data_loader = build_test_loader(cfg, self.task_cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/utils/engine_util.py", line 74, in build_test_loader
        loaders[name] = build_standard_valtest_loader(new_cfg, task_cfg, stage='test', multi_gpu_eval=multi_gpu)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 327, in build_standard_valtest_loader
        dataset = build_dataset_mapper(cfg, name=dataset_name, stage=stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 41, in build_dataset_mapper
        dataset_mapper = DATASETS_REGISTRY.get(name)(cfg, stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/config/config.py", line 211, in wrapped
        init_func(self, **explicit_args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 59, in __init__
        self.load_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 159, in load_data
        datalist = self.load_raw_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 219, in load_raw_data
        label = labelmapping[sensinfo[self.label_column - 1]]
    IndexError: list index out of range
    Traceback (most recent call last):
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 171, in <module>
        main(args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 113, in main
        trainer = build_engine(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/build.py", line 10, in build_engine
        engine = ENGINE_REGISTRY.get(cfg.ENGINE.NAME)(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_trainer.py", line 117, in __init__
        self.test_data_loader = build_test_loader(cfg, self.task_cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/utils/engine_util.py", line 74, in build_test_loader
        loaders[name] = build_standard_valtest_loader(new_cfg, task_cfg, stage='test', multi_gpu_eval=multi_gpu)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 327, in build_standard_valtest_loader
        dataset = build_dataset_mapper(cfg, name=dataset_name, stage=stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 41, in build_dataset_mapper
        dataset_mapper = DATASETS_REGISTRY.get(name)(cfg, stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/config/config.py", line 211, in wrapped
        init_func(self, **explicit_args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 59, in __init__
        self.load_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 159, in load_data
        datalist = self.load_raw_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 219, in load_raw_data
        label = labelmapping[sensinfo[self.label_column - 1]]
    IndexError: list index out of range
```

</p>
</details>
##################################################
<details><summary>GLUE_MRPC.yaml</summary>
<p>

```yaml
    _BASE_: "base.yaml"
    
    SHARED_TARGETS:
      - 
        NAME: 'MRPC'
        SHARED_TARGETS_CFG:
          FILE_PATH: '/mnt/14T-disk/code/Uni-Perceiver5/datasets/GLUE_classnames/MRPC_class_name_CLIP_with_endoftext.pkl'
          DISTRIBUTED: False
    TASKS:
      -
        NAME: MRPC
        DATASETS:
          TRAIN: 'GLUEDataset'
          TEST: 'GLUEDataset'
          #VAL: 'GLUEDataset'
          TASK_TYPE: 'text_classification'
          DATASET_NAME: 'MRPC'
          TARGET_SET: ['MRPC']
        DATALOADER:
          TRAIN_BATCH_SIZE: 16
          TEST_BATCH_SIZE: 64
          NUM_WORKERS: 4
          ANNO_FOLDER:  '/mnt/14T-disk/code/Uni-Perceiver5/datasets/bert_pretrain_data/glue_data/'
    
        MODEL:
          MAX_SEQ_LEN: 256
          TEMP_NAME: logit_scale_text_mlm
        LOSSES:
          NAMES: ['LabelSmoothingCrossEntropy', 'Accuracy']
          LABELSMOOTHING: 0.1
          # LOSS_WEIGHT: 1
          REDUCTION: 'mean'
          LOSS_FP32: False
        INFERENCE:
          NAME: 'GLUEEvaler'
          VOCAB: 'CLIP'
          GENERATION_MODE: False
    
    
      
    
    ENGINE:
      NAME: 'UnifiedTrainer'
    
    DATALOADER:
      USE_WEIGHTED_SAMPLER: True
      UNIFIED_DATASET: True 
      NUM_WORKERS: 16
    
    ######################################### MODEL #########################################
    MODEL:
      MODEL_EMA: False
      MODEL_EMA_DECAY: 0.9999
    
      
    ####################################### Optimizer #######################################
    SOLVER:
      NAME: 'Adam'
      MAX_ITER: 2500
      CHECKPOINT_PERIOD: 10000
      EVAL_PERIOD: 100
      CHECKPOINT_MAX_SAVE: 2
      BASE_LR: 0.00001
      BIAS_LR_FACTOR: 1.0
      WEIGHT_DECAY: 0.1
      WEIGHT_DECAY_NORM: 0.0
      WEIGHT_DECAY_BIAS: 0.0
      MOMENTUM: 0.9
      DAMPENING: 0.0
      NESTEROV: 0.0
      BETAS: [0.9, 0.98]
      EPS: 1e-8
      GRAD_CLIP: 0.5
      GRAD_CLIP_TYPE: 'norm'
      ACCUM_ITER: 0
      AMP_FP16: True
      APEX_FP16: False # dangerous
      WRITE_PERIOD: 20
      
    ####################################### lr scheduler ####################################### 
    LR_SCHEDULER:
      NAME: 'WarmupCosine'
      WARMUP: 150
      MIN_LR: 0.00000001
    
    
    
    find_unused_parameters: true
```

</p>
</details>

<details><summary>error</summary>
<p>

```
    Traceback (most recent call last):
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 171, in <module>
        main(args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 144, in main
        res = trainer.test(trainer.cfg, trainer.model, trainer.test_data_loader, trainer.test_evaluator, epoch=-1)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_trainer.py", line 520, in test
        return tester(self.task_cfg, model, test_data_loader, evaluator, epoch, self.amp_fp16, self.apex_fp16)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_tester.py", line 92, in tester
        results[task] = test_cls(task_cfg[task], model, test_data_loader[task], evaluator[task], epoch, amp_fp16, task)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_tester.py", line 239, in test_cls
        eval_res = evaluator.eval(results, epoch)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/evaluation/glue_evaler.py", line 56, in eval
        f1 = f1_score(y_true=labels, y_pred=preds)
      File "/home/whl/anaconda3/envs/uni-perceiver2/lib/python3.9/site-packages/sklearn/metrics/_classification.py", line 1123, in f1_score
        return fbeta_score(
      File "/home/whl/anaconda3/envs/uni-perceiver2/lib/python3.9/site-packages/sklearn/metrics/_classification.py", line 1261, in fbeta_score
        _, _, f, _ = precision_recall_fscore_support(
      File "/home/whl/anaconda3/envs/uni-perceiver2/lib/python3.9/site-packages/sklearn/metrics/_classification.py", line 1544, in precision_recall_fscore_support
        labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
      File "/home/whl/anaconda3/envs/uni-perceiver2/lib/python3.9/site-packages/sklearn/metrics/_classification.py", line 1365, in _check_set_wise_labels
        raise ValueError(
    ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].```

</p>
</details>
######################################################
##################################################
<details><summary>GLUE_QNLI.yaml</summary>
<p>


```yaml
_BASE_: "base.yaml"

SHARED_TARGETS:
  - 
    NAME: 'QNLI'
    SHARED_TARGETS_CFG:
      FILE_PATH: '/mnt/14T-disk/code/Uni-Perceiver5/datasets/GLUE_classnames/QNLI_class_name_CLIP_with_endoftext.pkl'
      DISTRIBUTED: False
TASKS:
  -
    NAME: QNLI
    DATASETS:
      TRAIN: 'GLUEDataset'
      TEST: 'GLUEDataset'
      #VAL: 'GLUEDataset'
      TASK_TYPE: 'text_classification'
      DATASET_NAME: 'QNLI'
      TARGET_SET: ['QNLI']
    DATALOADER:
      TRAIN_BATCH_SIZE: 16
      TEST_BATCH_SIZE: 64
      NUM_WORKERS: 4
      ANNO_FOLDER:  '/mnt/14T-disk/code/Uni-Perceiver5/datasets/bert_pretrain_data/glue_data/'

    MODEL:
      MAX_SEQ_LEN: 256
      TEMP_NAME: logit_scale_text_mlm
    LOSSES:
      NAMES: ['LabelSmoothingCrossEntropy', 'Accuracy']
      LABELSMOOTHING: 0.1
      # LOSS_WEIGHT: 1
      REDUCTION: 'mean'
      LOSS_FP32: False
    INFERENCE:
      NAME: 'GLUEEvaler'
      VOCAB: 'CLIP'
      GENERATION_MODE: False

ENGINE:
  NAME: 'UnifiedTrainer'

DATALOADER:
  USE_WEIGHTED_SAMPLER: True
  UNIFIED_DATASET: True 
  NUM_WORKERS: 16

######################################### MODEL #########################################
MODEL:
  MODEL_EMA: False
  MODEL_EMA_DECAY: 0.9999


####################################### Optimizer #######################################
SOLVER:
  NAME: 'Adam'
  MAX_ITER: 34000
  CHECKPOINT_PERIOD: 200000
  EVAL_PERIOD: 2000
  CHECKPOINT_MAX_SAVE: 2
  BASE_LR: 0.00001
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY: 0.1
  WEIGHT_DECAY_NORM: 0.0
  WEIGHT_DECAY_BIAS: 0.0
  MOMENTUM: 0.9
  DAMPENING: 0.0
  NESTEROV: 0.0
  BETAS: [0.9, 0.98]
  EPS: 1e-8
  GRAD_CLIP: 0.5
  GRAD_CLIP_TYPE: 'norm'
  ACCUM_ITER: 0
  AMP_FP16: True
  APEX_FP16: False # dangerous
  WRITE_PERIOD: 20
  
####################################### lr scheduler ####################################### 
LR_SCHEDULER:
  NAME: 'WarmupCosine'
  WARMUP: 2000
  MIN_LR: 0.00000001



find_unused_parameters: true
```

</p>
</details>

<details><summary>error</summary>
<p>

```
    Traceback (most recent call last):
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 171, in <module>
        main(args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 113, in main
        trainer = build_engine(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/build.py", line 10, in build_engine
        engine = ENGINE_REGISTRY.get(cfg.ENGINE.NAME)(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_trainer.py", line 117, in __init__
        self.test_data_loader = build_test_loader(cfg, self.task_cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/utils/engine_util.py", line 74, in build_test_loader
        loaders[name] = build_standard_valtest_loader(new_cfg, task_cfg, stage='test', multi_gpu_eval=multi_gpu)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 327, in build_standard_valtest_loader
        dataset = build_dataset_mapper(cfg, name=dataset_name, stage=stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 41, in build_dataset_mapper
        dataset_mapper = DATASETS_REGISTRY.get(name)(cfg, stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/config/config.py", line 211, in wrapped
        init_func(self, **explicit_args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 59, in __init__
        self.load_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 159, in load_data
        datalist = self.load_raw_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 221, in load_raw_data
        label = 1.0 if sensinfo[self.label_column - 1] == "entailment" else 0.0
    IndexError: list index out of range
    Traceback (most recent call last):
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 171, in <module>
        main(args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 113, in main
        trainer = build_engine(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/build.py", line 10, in build_engine
        engine = ENGINE_REGISTRY.get(cfg.ENGINE.NAME)(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_trainer.py", line 117, in __init__
        self.test_data_loader = build_test_loader(cfg, self.task_cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/utils/engine_util.py", line 74, in build_test_loader
        loaders[name] = build_standard_valtest_loader(new_cfg, task_cfg, stage='test', multi_gpu_eval=multi_gpu)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 327, in build_standard_valtest_loader
        dataset = build_dataset_mapper(cfg, name=dataset_name, stage=stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 41, in build_dataset_mapper
        dataset_mapper = DATASETS_REGISTRY.get(name)(cfg, stage)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/config/config.py", line 211, in wrapped
        init_func(self, **explicit_args)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 59, in __init__
        self.load_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 159, in load_data
        datalist = self.load_raw_data(cfg)
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 221, in load_raw_data
        label = 1.0 if sensinfo[self.label_column - 1] == "entailment" else 0.0
    IndexError: list index out of range
```

</p>
</details>
######################################################
##################################################
QQP:
<details><summary>error</summary>
<p>

```
    Traceback (most recent call last):
    Traceback (most recent call last):
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 171, in <module>
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 171, in <module>
            main(args)main(args)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 113, in main
      File "/mnt/14T-disk/code/Uni-Perceiver5/main.py", line 113, in main
            trainer = build_engine(cfg)trainer = build_engine(cfg)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/build.py", line 10, in build_engine
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/build.py", line 10, in build_engine
            engine = ENGINE_REGISTRY.get(cfg.ENGINE.NAME)(cfg)engine = ENGINE_REGISTRY.get(cfg.ENGINE.NAME)(cfg)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_trainer.py", line 117, in __init__
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/engine/unified_trainer.py", line 117, in __init__
            self.test_data_loader = build_test_loader(cfg, self.task_cfg)self.test_data_loader = build_test_loader(cfg, self.task_cfg)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/utils/engine_util.py", line 74, in build_test_loader
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/utils/engine_util.py", line 74, in build_test_loader
            loaders[name] = build_standard_valtest_loader(new_cfg, task_cfg, stage='test', multi_gpu_eval=multi_gpu)loaders[name] = build_standard_valtest_loader(new_cfg, task_cfg, stage='test', multi_gpu_eval=multi_gpu)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 327, in build_standard_valtest_loader
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 327, in build_standard_valtest_loader
            dataset = build_dataset_mapper(cfg, name=dataset_name, stage=stage)dataset = build_dataset_mapper(cfg, name=dataset_name, stage=stage)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 41, in build_dataset_mapper
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/build.py", line 41, in build_dataset_mapper
            dataset_mapper = DATASETS_REGISTRY.get(name)(cfg, stage)dataset_mapper = DATASETS_REGISTRY.get(name)(cfg, stage)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/config/config.py", line 211, in wrapped
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/config/config.py", line 211, in wrapped
            init_func(self, **explicit_args)init_func(self, **explicit_args)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 59, in __init__
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 59, in __init__
            self.load_data(cfg)self.load_data(cfg)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 159, in load_data
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 159, in load_data
            datalist = self.load_raw_data(cfg)datalist = self.load_raw_data(cfg)
    
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 225, in load_raw_data
      File "/mnt/14T-disk/code/Uni-Perceiver5/uniperceiver/datasets/task_dataset/GLUE.py", line 225, in load_raw_data
            label = float(sensinfo[self.label_column - 1])label = float(sensinfo[self.label_column - 1])
    
    IndexErrorIndexError: : list index out of rangelist index out of range
```

</p>
</details>

**Comment by Lechatelia** [comment]
sorry for this error. I will check it as soon as possible.

**Comment by Lechatelia** [comment]
初步看来应该是glue数据的标注文件处理之后存在着差异，我们是参考了[fairseq的前处理方式](https://github.com/fundamentalvision/Uni-Perceiver/blob/main/data/prepare_data.md)
这里有详细的介绍[prepare_data.md](https://github.com/facebookresearch/fairseq/blob/main/examples/roberta/README.glue.md)

 您方便将某一个任务的文件发给我吗？比如 /glue_data/CoLA/processed/train.tsv
可以发给我的邮箱 lechatelia@stu.xjtu.edu.cn

**Comment by hongliang-wei** [comment]
抱歉，我在问题里可能没有说清楚，
我在config中添加TASKS.DATASETS.TEST: 'GLUEdataset' 来在测试集上运行时，程序会出错。不添加&nbsp;TASKS.DATASETS.TEST: 'GLUEdataset'&nbsp;时程序是可以正常训练的。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fundamentalvision/Uni-Perceiver"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月14日(星期二) 晚上7:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fundamentalvision/Uni-Perceiver] 在GLUE数据集上测试，程序报错 (Issue #11)





 
初步看来应该是glue数据的标注文件处理之后存在着差异，我们是参考了fairseq的前处理方式这里有详细的介绍) （prepare_data.md
 
您方便将某一个任务的文件发给我吗？比如 /glue_data/CoLA/processed/train.tsv
 可以发给我的邮箱 ***@***.***

**Comment by Lechatelia** [comment]
不好意思 这份code没有验证测试集是否存在问题，  我会尽快验证下GLUE测试集涉及到的code是否存在问题，
